name: 3 Build custom version

on:
  workflow_call:
    inputs:
      build_base:
        type: string
        required: true
      version:
        type: string
        required: true        
  workflow_dispatch:
    branches:
      - master
    inputs:             
      build_base:
        type: choice
        description: 'Build is based on:'
        required: true
        options:
        - current version on master
        - current version on branch
        - specific version(tag)
        default: current version on branch
      version:
        description: 'Branch Version or Specific Version(tag):'
        required: false
        default: '3.0.0'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Install Maven
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: GIT comitter configuration
      run: |
        git config --global user.email "glaucio.porcidesczekailo@atos.net"
        git config --global user.name "Glaucio Czekailo"
    - name: GIT check for branch
      run: |       
        CALLED_VIA_BUILDRC=false
        
        if [[ "${{ inputs.build_base }}" == "current version on master" ]]; then
            echo "Will use latest version on master for build"            
        elif [[ "${{ inputs.build_base }}" == "current version on branch" ]]; then
            BRANCH="VERSION-${{ inputs.version }}"
            echo "Will use latest on branch $BRANCH"            
        elif [[ "${{ inputs.build_base }}" == "specific version(tag)" ]]; then
            TAG="${{ inputs.version }}"
            echo "Will checkout and use the following tag $TAG" 
        elif [[ "${{ inputs.build_base }}" == "next" || "${{ inputs.build_base }}" == "final" ]]; then
            #hidden value 
            echo "Workflow was called from Build Release Candidate"  
            CALLED_VIA_BUILDRC=true
            echo "Will build ${{ inputs.version }}"
        else
            echo "Unknown option. Will exit."
            exit 1
        fi
        
        echo "CALLED_VIA_BUILDRC=$CALLED_VIA_BUILDRC" >> $GITHUB_ENV 
        
    - name: Pre-build version preparation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY         
        ON_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Running on branch $ON_BRANCH"
        
        if [[ "$CALLED_VIA_BUILDRC" == "true" ]]; then
            source ci/build_release_candidate.sh
            if [[ "${{ inputs.build_base }}" == "final" ]]; then
                echo "Will build final release"
                buildPreparation "${{ inputs.version }}" final
            else
                buildPreparation "${{ inputs.version }}"
            fi
        else
            echo "Workflow called via GitHub Action UI"
        fi
        
    - name: Run build script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ON_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Running on branch $ON_BRANCH"
        
    - name: Post-build upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ON_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Running on branch $ON_BRANCH"
        
                
        
        
