name: Z-1 Create Release Branch

on:
  workflow_dispatch:
    branches:
      - release-master
    inputs:
      release_type:
        type: choice
        description: 'Release type'
        required: true
        options:
        - major
        - minor
        - patch
        default: 'patch'
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: GIT committer configuration
      run: |
        git config --global user.email "glaucio.porcidesczekailo@atos.net"
        git config --global user.name "Glaucio Czekailo"
    - name: Run CI script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ON_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Workflow is running on branch $ON_BRANCH"
        echo "Request: create a ${{ github.event.inputs.release_type }} release branch"
        bash ci/releaseWF_create_release_branch.sh ${{ github.event.inputs.release_type }}
